;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        comment-region
        extend-selection
        fill-paragraph
        forward-sexp
        indent-for-tab-command
        indent-region
        isearch-forward-regexp
        js2-beginning-of-line
        js2-end-of-line
        kill-region
        nxml-backward-element
        nxml-electric-slash
        nxml-finish-element
        nxml-forward-element
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-cycle
        org-delete-char
        org-return-indent
        org-self-insert-command
        org-shiftright
        python-backspace
        python-electric-colon
        save-some-buffers
        shell-command
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        ido-switch-buffer
        isearch-other-control-char
        isearch-printing-char
        js2-mode-show-node
        magit-status
        mouse-set-region
        wdired-finish-edit
        ))
