(deftheme aj-jsc-light
  "Modified color theme, original by John S Cooper, created 2000-06-08.")

(setq-default mode-line-buffer-identification
              (list (propertize "%12b" 'face
                                (list :weight 'bold
                                      :foreground "#222222"))))

(let (
      (color-bg "#eeeedd")
      (color-fg "#333344")
      (term-black "#2f343f")
      (term-red "#b84a62")
      (term-green "#2f7d32")
      (term-yellow "#8a6d1d")
      (term-blue "#2c67b1")
      (term-magenta "#8b4fb0")
      (term-cyan "#007a7c")
      (term-white "#6f6a5f")
      (term-bright-black "#8a8478")
      (term-bright-red "#cf4f6f")
      (term-bright-green "#3b8f3f")
      (term-bright-yellow "#a27a1f")
      (term-bright-blue "#3a74bf")
      (term-bright-magenta "#9a5fc2")
      (term-bright-cyan "#148f91")
      (term-bright-white "#4f4a40")
      )

  (custom-theme-set-faces
   'aj-jsc-light
   `(default ((t (nil))))
   `(default ((t ( :foreground ,color-fg :background ,color-bg))))
   `(cursor  ((t (:background "Red"))))
   `(highlight ((t (:background "#e3e3d3"))))
   `(highlight-indentation-face ((t (:inherit highlight))))
   `(highlight-indentation-current-column-face ((t (:background "#d3d3c3"))))
   `(fringe ((t (:inherit highlight))))
   `(hl-line-face ((t (:inherit highlight))))
   `(hl-line ((t (:inherit highlight))))

   ;; Swiper
   `(swiper-line-face ((t (:background "yellow"))))

   ;; idle-highlight-in-visible-buffers-mode
   `(idle-highlight-in-visible-buffers ((t (:background "pink" :underline t))))


   ;; Typography
   `(bold ((t (:bold t))))
   `(bold-italic ((t (:italic t :bold t))))
   `(italic ((t (:italic t))))
   `(underline ((t (:underline t))))

   ;; LSP
   `(lsp-face-highlight-read ((t (:background "#d3d3c3"))))
   `(lsp-face-highlight-textual ((t (:background "#d3d388"))))
   `(lsp-face-highlight-write ((t (:background "#88d3c3"))))

   `(lsp-ui-sideline-code-action((t (:background "#88d3c3"))))

   ;; Error warning
   `(flyspell-incorrect ((t (:inherit default :underline "OrangeRed"))))
   `(flyspell-duplicate ((t (:inherit default :underline "Gold3"))))

   ;; Font-lock
   `(font-lock-builtin-face ((t (:foreground "Orchid"))))
   `(font-lock-comment-face ((t (:italic t :bold t :foreground "#999988"))))
   `(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :bold t :background "#ddddcc"))))
   `(font-lock-constant-face ((t (:foreground "navy"))))
   `(font-lock-function-name-face ((t (:bold nil :foreground "Blue"))))
   `(font-lock-keyword-face ((t (:bold t :foreground "Purple"))))
   `(font-lock-string-face ((t (:foreground "Green4"))))
   `(font-lock-type-face ((t (:foreground "Navy"))))
   `(font-lock-variable-name-face ((t (:foreground "Tan4"))))
   `(font-lock-warning-face ((t (:foreground "OrangeRed"))))

   ;; LaTeX
   `(font-latex-sedate ((t (:inherit font-lock-keyword-face))))
   `(font-latex-string-face ((t (:inherit font-lock-string-face))))

   ;; Comint
   `(comint-highlight-input ((t (:inherit font-lock-keyword-face))))
   `(comint-highlight-prompt ((t (:inherit font-lock-function-name-face))))
   `(compilation-info ((t (:inherit font-lock-function-name-face))))
   `(ansi-color-black ((t (:foreground ,term-black :background unspecified))))
   `(ansi-color-red ((t (:foreground ,term-red :background unspecified))))
   `(ansi-color-green ((t (:foreground ,term-green :background unspecified))))
   `(ansi-color-yellow ((t (:foreground ,term-yellow :background unspecified))))
   `(ansi-color-blue ((t (:foreground ,term-blue :background unspecified))))
   `(ansi-color-magenta ((t (:foreground ,term-magenta :background unspecified))))
   `(ansi-color-cyan ((t (:foreground ,term-cyan :background unspecified))))
   `(ansi-color-white ((t (:foreground ,term-white :background unspecified))))
   `(ansi-color-bright-black ((t (:foreground ,term-bright-black :background unspecified))))
   `(ansi-color-bright-red ((t (:foreground ,term-bright-red :background unspecified))))
   `(ansi-color-bright-green ((t (:foreground ,term-bright-green :background unspecified))))
   `(ansi-color-bright-yellow ((t (:foreground ,term-bright-yellow :background unspecified))))
   `(ansi-color-bright-blue ((t (:foreground ,term-bright-blue :background unspecified))))
   `(ansi-color-bright-magenta ((t (:foreground ,term-bright-magenta :background unspecified))))
   `(ansi-color-bright-cyan ((t (:foreground ,term-bright-cyan :background unspecified))))
   `(ansi-color-bright-white ((t (:foreground ,term-bright-white :background unspecified))))
   `(ansi-color-bold ((t (:weight bold))))
   `(ansi-color-faint ((t (:foreground "#9b9588"))))
   `(ansi-color-italic ((t (:slant italic))))
   `(ansi-color-underline ((t (:underline t))))
   `(ansi-color-inverse ((t (:inverse-video t))))

   ;; Terminal colors for light backgrounds
   `(term-color-black ((t (:foreground ,term-black :background ,term-black))))
   `(term-color-red ((t (:foreground ,term-red :background ,term-red))))
   `(term-color-green ((t (:foreground ,term-green :background ,term-green))))
   `(term-color-yellow ((t (:foreground ,term-yellow :background ,term-yellow))))
   `(term-color-blue ((t (:foreground ,term-blue :background ,term-blue))))
   `(term-color-magenta ((t (:foreground ,term-magenta :background ,term-magenta))))
   `(term-color-cyan ((t (:foreground ,term-cyan :background ,term-cyan))))
   `(term-color-white ((t (:foreground ,term-white :background ,term-white))))
   `(term-color-bright-black ((t (:foreground ,term-bright-black :background ,term-bright-black))))
   `(term-color-bright-red ((t (:foreground ,term-bright-red :background ,term-bright-red))))
   `(term-color-bright-green ((t (:foreground ,term-bright-green :background ,term-bright-green))))
   `(term-color-bright-yellow ((t (:foreground ,term-bright-yellow :background ,term-bright-yellow))))
   `(term-color-bright-blue ((t (:foreground ,term-bright-blue :background ,term-bright-blue))))
   `(term-color-bright-magenta ((t (:foreground ,term-bright-magenta :background ,term-bright-magenta))))
   `(term-color-bright-cyan ((t (:foreground ,term-bright-cyan :background ,term-bright-cyan))))
   `(term-color-bright-white ((t (:foreground ,term-bright-white :background ,term-bright-white))))
   `(vterm-color-black ((t (:foreground ,term-black :background ,term-black))))
   `(vterm-color-red ((t (:foreground ,term-red :background ,term-red))))
   `(vterm-color-green ((t (:foreground ,term-green :background ,term-green))))
   `(vterm-color-yellow ((t (:foreground ,term-yellow :background ,term-yellow))))
   `(vterm-color-blue ((t (:foreground ,term-blue :background ,term-blue))))
   `(vterm-color-magenta ((t (:foreground ,term-magenta :background ,term-magenta))))
   `(vterm-color-cyan ((t (:foreground ,term-cyan :background ,term-cyan))))
   `(vterm-color-white ((t (:foreground ,term-white :background ,term-white))))
   `(vterm-color-bright-black ((t (:foreground ,term-bright-black :background ,term-bright-black))))
   `(vterm-color-bright-red ((t (:foreground ,term-bright-red :background ,term-bright-red))))
   `(vterm-color-bright-green ((t (:foreground ,term-bright-green :background ,term-bright-green))))
   `(vterm-color-bright-yellow ((t (:foreground ,term-bright-yellow :background ,term-bright-yellow))))
   `(vterm-color-bright-blue ((t (:foreground ,term-bright-blue :background ,term-bright-blue))))
   `(vterm-color-bright-magenta ((t (:foreground ,term-bright-magenta :background ,term-bright-magenta))))
   `(vterm-color-bright-cyan ((t (:foreground ,term-bright-cyan :background ,term-bright-cyan))))
   `(vterm-color-bright-white ((t (:foreground ,term-bright-white :background ,term-bright-white))))
   `(vterm-color-underline ((t (:underline t))))
   `(vterm-color-inverse-video ((t (:inverse-video t))))

   ;; DIFF
   `(diff-header ((t (:inherit highlight))))
   `(diff-hunk-header ((t (:inherit diff-header))))

   `(diff-removed ((t (:foreground "#cc0077" :weight bold))))
   `(diff-indicator-removed ((t (:inherit diff-removed))))

   `(diff-added ((t (:foreground "#77cc00" :weight bold))))
   `(diff-indicator-added ((t (:inherit diff-added))))
   `(diff-refine-change ((t (:inherit highlight))))


   ;; Org-mode
   `(org-checkbox ((t (:inherit highlight))))
   `(org-link ((t (:foreground "#0077CC" :underline nil))))
   `(org-date ((t (:foreground "#7700cc"))))
   `(org-todo ((t (:foreground "#cc0077" :weight bold))))
   `(org-done ((t (:foreground "#77cc00" :weight bold))))
   `(org-upcoming-deadline ((t (:foreground "chocolate" :weight bold))))
   `(org-level-1 ((t (:inherit font-lock-constant-face :height 1.3 :weight bold))))
   `(org-level-2 ((t (:inherit font-lock-keyword-face :height 1.1 :weight bold))))
   `(org-level-3 ((t (:inherit font-lock-variable-name-face :weight bold))))
   `(org-level-4 ((t (:inherit font-lock-comment-face :weight bold))))
   `(markdown-header-face-1 ((t (:inherit font-lock-constant-face :height 1.3 :weight bold))))
   `(markdown-header-face-2 ((t (:inherit font-lock-keyword-face :height 1.1 :weight bold))))
   `(markdown-header-face-3 ((t (:inherit font-lock-variable-name-face :weight bold))))
   `(markdown-header-face-4 ((t (:inherit font-lock-comment-face :weight bold))))
   `(jabber-chat-prompt-foreign ((t (:inherit font-lock-constant-face))))
   `(jabber-chat-prompt-local ((t (:inherit font-lock-comment-face))))
   `(mode-line ((t (:background "plum" :foreground "black" :underline nil :box (:line-width 1 :color "plum3" :style nil)))))
   `(mode-line-inactive ((t (:background "#e3e3d3" :underline nil :foreground "black" :box (:line-width 1 :color "gray77" :style nil)))))
   `(modeline-buffer-id ((t (:background "plum" :foreground "black"))))
   `(modeline-mousable ((t (:background "plum" :foreground "black"))))
   `(modeline-mousable-minor-mode ((t (:background "plum" :foreground "black"))))
   ``(region ((t (:background "plum"))))
   `(dired-directory ((t (:inherit font-lock-function-name-face))))
   `(dired-header ((t (:inherit font-lock-keyword-face :height 1.2))))
   `(ido-subdir ((t (:inherit font-lock-function-name-face))))
   `(ido-only-match ((t (:inherit font-lock-string-face :weight bold))))
   `(ido-first-match ((t (:inherit font-lock-string-face))))
   `(ido-first-match-face ((t (:inherit font-lock-string-face))))
   `(minibuffer-prompt ((t (:foreground "black"))))
   `(nxml-element-local-name ((t (:foreground "#07C" ))))
   `(nxml-tag-delimiter ((t (:inherit nxml-element-local-name))))
   `(nxml-attribute-local-name ((t (:foreground "#7C0" ))))
   `(nxml-attribute-value ((t (:inherit font-lock-string-face))))
   `(woman-bold ((t (:foreground "#07C"))))
   `(custom-button-face ((t (nil))))
   `(custom-changed-face ((t (:background "blue" :foreground "white"))))
   `(custom-documentation-face ((t (nil))))
   `(custom-face-tag-face ((t (:underline t))))
   `(custom-group-tag-face ((t (:underline t :foreground "blue"))))
   `(custom-group-tag-face-1 ((t (:underline t :foreground "red"))))
   `(custom-invalid-face ((t (:background "red" :foreground "yellow"))))
   `(custom-modified-face ((t (:background "blue" :foreground "white"))))
   `(custom-rogue-face ((t (:background "black" :foreground "pink"))))
   `(custom-saved-face ((t (:underline t))))
   `(custom-set-face ((t (:background "white" :foreground "blue"))))
   `(custom-state-face ((t (:foreground "dark green"))))
   `(custom-variable-button-face ((t (:underline t :bold t))))
   `(custom-variable-tag-face ((t (:underline t :foreground "blue"))))
   `(gnus-cite-attribution-face ((t (:italic t))))
   `(gnus-cite-face-1 ((t (:foreground "MidnightBlue"))))
   `(gnus-cite-face-10 ((t (:foreground "medium purple"))))
   `(gnus-cite-face-11 ((t (:foreground "turquoise"))))
   `(gnus-cite-face-2 ((t (:foreground "firebrick"))))
   `(gnus-cite-face-3 ((t (:foreground "dark green"))))
   `(gnus-cite-face-4 ((t (:foreground "OrangeRed"))))
   `(gnus-cite-face-5 ((t (:foreground "dark khaki"))))
   `(gnus-cite-face-6 ((t (:foreground "dark violet"))))
   `(gnus-cite-face-7 ((t (:foreground "SteelBlue4"))))
   `(gnus-cite-face-8 ((t (:foreground "magenta"))))
   `(gnus-cite-face-9 ((t (:foreground "violet"))))
   `(gnus-emphasis-bold ((t (:bold t))))
   `(gnus-emphasis-bold-italic ((t (:italic t :bold t))))
   `(gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
   `(gnus-emphasis-italic ((t (:italic t))))
   `(gnus-emphasis-underline ((t (:underline t))))
   `(gnus-emphasis-underline-bold ((t (:underline t :bold t))))
   `(gnus-emphasis-underline-bold-italic ((t (:underline t :italic t :bold t))))
   `(gnus-emphasis-underline-italic ((t (:underline t :italic t))))
   `(gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
   `(gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3"))))
   `(gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
   `(gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3"))))
   `(gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
   `(gnus-group-mail-3-face ((t (:bold t :foreground "magenta4"))))
   `(gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
   `(gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4"))))
   `(gnus-group-news-1-empty-face ((t (:foreground "blue2"))))
   `(gnus-group-news-1-face ((t (:bold t :foreground "blue2"))))
   `(gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
   `(gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4"))))
   `(gnus-group-news-3-empty-face ((t (nil))))
   `(gnus-group-news-3-face ((t (:bold t))))
   `(gnus-group-news-4-empty-face ((t (nil))))
   `(gnus-group-news-4-face ((t (:bold t))))
   `(gnus-group-news-5-empty-face ((t (nil))))
   `(gnus-group-news-5-face ((t (:bold t))))
   `(gnus-group-news-6-empty-face ((t (nil))))
   `(gnus-group-news-6-face ((t (:bold t))))
   `(gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
   `(gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen"))))
   `(gnus-header-content-face ((t (:italic t :foreground "blue"))))
   `(gnus-header-from-face ((t (:foreground "red3"))))
   `(gnus-header-name-face ((t (:foreground "red3"))))
   `(gnus-header-newsgroups-face ((t (:italic t :foreground "MidnightBlue"))))
   `(gnus-header-subject-face ((t (:bold t :foreground "red"))))
   `(gnus-signature-face ((t (:foreground "pink"))))
   `(gnus-splash-face ((t (:foreground "Brown"))))
   `(gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
   `(gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue"))))
   `(gnus-summary-high-read-face ((t (:bold t :foreground "navy"))))
   `(gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick"))))
   `(gnus-summary-high-unread-face ((t (:bold t :foreground "blue"))))
   `(gnus-summary-low-ancient-face ((t (:italic t :foreground "RoyalBlue"))))
   `(gnus-summary-low-read-face ((t (:italic t :foreground "DarkGreen"))))
   `(gnus-summary-low-ticked-face ((t (:italic t :foreground "firebrick"))))
   `(gnus-summary-low-unread-face ((t (:italic t))))
   `(gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
   `(gnus-summary-normal-read-face ((t (:foreground "red3"))))
   `(gnus-summary-normal-ticked-face ((t (:foreground "black"))))
   `(gnus-summary-normal-unread-face ((t (:bold t :foreground "red3"))))
   `(gnus-summary-selected-face ((t (:underline t))))
   `(makefile-space-face ((t (:background "hotpink"))))
   `(message-cited-text-face ((t (:foreground "red"))))
   `(message-header-cc-face ((t (:foreground "MidnightBlue"))))
   `(message-header-name-face ((t (:foreground "cornflower blue"))))
   `(message-header-newsgroups-face ((t (:italic t :bold t :foreground "blue4"))))
   `(message-header-other-face ((t (:foreground "steel blue"))))
   `(message-header-subject-face ((t (:bold t :foreground "navy blue"))))
   `(message-header-to-face ((t (:bold t :foreground "MidnightBlue"))))
   `(message-header-xheader-face ((t (:foreground "blue"))))
   `(message-mml-face ((t (:foreground "ForestGreen"))))
   `(message-separator-face ((t (:foreground "brown"))))
   `(secondary-selection ((t (:background "palegreen"))))
   `(show-paren-match-face ((t (:background "plum"))))
   `(show-paren-mismatch-face ((t (:background "navy" :foreground "white"))))
   `(speedbar-button-face ((t (:foreground "green4"))))
   `(speedbar-directory-face ((t (:foreground "blue4"))))
   `(speedbar-file-face ((t (:foreground "cyan4"))))
   `(speedbar-highlight-face ((t (:background "green"))))
   `(speedbar-selected-face ((t (:underline t :foreground "red"))))
   `(speedbar-tag-face ((t (:foreground "brown"))))
   `(widget-button-face ((t (:bold t))))
   `(widget-button-pressed-face ((t (:foreground "red"))))
   `(widget-documentation-face ((t (:foreground "dark green"))))
   `(widget-field-face ((t (:background "gray85"))))
   `(widget-inactive-face ((t (:foreground "dim gray"))))
   `(widget-single-line-field-face ((t (:background "gray85"))))
   ))

(provide-theme 'aj-jsc-light)
